### ISSUE TITLE
Tonkeeper error "Wrong network"

### ISSUE THREAD

**Issue by nurikk** [nessshon/aiogram-tonconnect#1]
Hello! Thanks for your fantastic library! I'm using it my project.

But onfourtunatly transactions functionality doesn't work for Tonkeeper wallet.

I use official bot `https://t.me/aiogramTONConnectBot/` to test this workflow, if you connect Tonkeeper wallet and try to send any amount of TON, you'll get error "Wrong network"

https://github.com/nessshon/aiogram-tonconnect/assets/1525421/2be74075-09d6-4f95-a9f1-06f5f2e6c0df

**Comment by nurikk** [comment]
I've found the issue, 

if we don't specify network for `TONTransferTransaction`, then default value `https://github.com/nessshon/aiogram-tonconnect/blob/40515deb6b0d4d9955ff05d7f9bf97c2c6ef6f13/aiogram_tonconnect/tonconnect/models.py#L172`

will be taken, but class `CHAIN` inherited from `IntEnum` which will cast `"-239"` (string) into `-239` (int)
which causes Tonkepeer to reject transfer

**Comment by nessshon** [comment]
@nurikk Hi!

Thank you for identifying the issue. I have applied the update to resolve this problem. Please install the new version 0.13.8.
```bash
pip install --upgrade aiogram-tonconnect
```

**Comment by nurikk** [comment]
> @nurikk Hi!
> 
> Thank you for identifying the issue. I have applied the update to resolve this problem. Please install the new version 0.13.8.
> 
> ```shell
> pip install --upgrade aiogram-tonconnect
> ```

Terrific speed! Thanks for prompt response ☺️
